### ISSUE TITLE
[Tracking] Unsupported features (as of Ruby 3.2)

### ISSUE THREAD

**Issue by reese** [samphippen/rubyfmt#399]
`rubyfmt` currently doesn't support many of the major syntax additions of the last year. We historically targeted 2.7, but with the 2.7 EOL looming and the addition of so many features in 3.0-3.2, we should start looking at supporting the new features. This ticket is mostly a tracking issue to have visibility on the progress here.

- [x] [Pattern matching](https://rubyreferences.github.io/rubychanges/3.0.html#pattern-matching) (existed in 2.7 but stabilized in 3)
  - [x] [2.7 style pattern matching](https://rubyreferences.github.io/rubychanges/2.7.html#pattern-matching)
  - [x] [Rightward assignment](https://rubyreferences.github.io/rubychanges/3.0.html#one-line-pattern-matching-with-)
  - [x] [`in` matching](https://rubyreferences.github.io/rubychanges/3.0.html#in-as-a-truefalse-check)
  - [x] [Pin operator](https://rubyreferences.github.io/rubychanges/3.1.html#expressions-and-non-local-variables-allowed-in-pin-operator-)
- [x] [Endless methods](https://rubyreferences.github.io/rubychanges/3.0.html#endless-method-definition)
  - Implemented in #405 
- [x] [Hash literal value omissions](https://rubyreferences.github.io/rubychanges/3.1.html#values-in-hash-literals-and-keyword-arguments-can-be-omitted)
  - Implemented in #404
- [x] [Anonymous block args](https://rubyreferences.github.io/rubychanges/3.1.html#anonymous-block-argument)
  - Implemented in #471

**Comment by rattrayalex** [comment]
Hi @reese! I'd love to fund work on this if you're open to sponsorship / contract work?

**Comment by reese** [comment]
Hi @rattrayalex, thanks for reaching out! I'm currently on a bit of a break from more formal work arrangements and so probably won't have the capacity for sponsorship or contract work at the moment. If anyone else would has interest in working on this, I'd be more than happy to give pointers in the codebase for how any of this could be done, and #456 does a pretty good chunk of the heavy lifting for getting pattern matching over the line anyways, so I hope that with that it's actually not a _huge_ amount of work.

(It may also be relevant to check with @fables-tales to see if any of the folks currently working at Stripe have this work on their radar, since I know there were at least very-early-stage discussions about pattern matching a few months ago.)

**Comment by reese** [comment]
Note for any watchers: all of these features are implemented (see #686 and #687) as part of the Prism rewrite, so I imagine these will make it out in a released version soon enough once we've done some more testing.

**Comment by reese** [comment]
`v0.12.0` is out with pattern matching support, so I'm gonna close this out! ✅
